SET NAMES utf8;
SET foreign_key_checks = 0;
SET time_zone = SYSTEM;
SET sql_mode = NO_AUTO_VALUE_ON_ZERO;
DROP TABLE IF EXISTS pivo;
DROP TABLE IF EXISTS slad;
DROP TABLE IF EXISTS chmel;
DROP TABLE IF EXISTS kvasnice;
DROP TABLE IF EXISTS hodnoceni;
DROP TABLE IF EXISTS hodnocenihospoda;
DROP TABLE IF EXISTS uzivatel;
DROP TABLE IF EXISTS hospoda;
DROP TABLE IF EXISTS pivovar;
DROP TABLE IF EXISTS sladek;
CREATE TABLE pivo(ID_pivo INT NOT NULL AUTO_INCREMENT,nazev VARCHAR(25) NOT NULL,stupen_EBC INT NOT NULL,styl_kvaseni VARCHAR(25) NOT NULL,typ_piva VARCHAR(25) NOT NULL,obsah_alkoholu INT NOT NULL, ID_slad INT NOT NULL , ID_chmel INT NOT NULL,ID_kvasnice INT NOT NULL , ID_sladka INT NOT NULL ,ID_pivovar INT NOT NULL , PRIMARY KEY (ID_pivo), KEY ID_kvasnice (ID_kvasnice),KEY ID_chmel (ID_chmel) ,KEY ID_slad (ID_slad), KEY ID_sladka (ID_sladka), KEY ID_pivovaru (ID_pivovar)) ENGINE=InnoDB;
CREATE TABLE slad(ID_slad INT NOT NULL AUTO_INCREMENT,barva VARCHAR(25) NOT NULL,puvod VARCHAR(25) NOT NULL,extrakt VARCHAR(25) NOT NULL, PRIMARY KEY (ID_slad)) ENGINE=InnoDB;
CREATE TABLE chmel(ID_chmel INT NOT NULL AUTO_INCREMENT,puvod VARCHAR(25) NOT NULL,doba_sklizne VARCHAR(25) NOT NULL,aroma VARCHAR(25) NOT NULL,horkost INT NOT NULL,podil_alfa_kyselin INT NOT NULL, PRIMARY KEY (ID_chmel)) ENGINE=InnoDB;
CREATE TABLE kvasnice(ID_kvasnice INT NOT NULL AUTO_INCREMENT,skupenstvi VARCHAR(25) NOT NULL,typ_kvaseni VARCHAR(25) NOT NULL, PRIMARY KEY(ID_kvasnice)) ENGINE=InnoDB;
CREATE TABLE hodnoceni(ID_pivo INT NOT NULL,login VARCHAR(25) NOT NULL,znamka INT NOT NULL,datum DATE NOT NULL,cas VARCHAR(25) NOT NULL, PRIMARY KEY (ID_pivo,login)) ENGINE=InnoDB;
CREATE TABLE hodnocenihospoda(ID_hospoda INT NOT NULL,login VARCHAR(25) NOT NULL,znamka INT NOT NULL,datum DATE NOT NULL,cas VARCHAR(25) NOT NULL, PRIMARY KEY (ID_hospoda,login)) ENGINE=InnoDB;
CREATE TABLE hospoda(ID_hospoda INT NOT NULL AUTO_INCREMENT,nazev VARCHAR(25) NOT NULL,adr_mesto VARCHAR(30) NOT NULL,adr_ulice VARCHAR(30) NOT NULL,adr_cislo_domu INT NOT NULL,PSC INT NOT NULL, PRIMARY KEY (ID_hospoda)) ENGINE=InnoDB;
CREATE TABLE pivovar(ID_pivovar INT NOT NULL AUTO_INCREMENT,nazev VARCHAR(25) NOT NULL,adr_mesto VARCHAR(30) NOT NULL,adr_ulice VARCHAR(30) NOT NULL,adr_cislo_domu INT NOT NULL,PSC INT (5) NOT NULL, PRIMARY KEY (ID_pivovar)) ENGINE=InnoDB;
CREATE TABLE uzivatel(login VARCHAR(25) NOT NULL,heslo VARCHAR(25) NOT NULL, PRIMARY KEY (login)) ENGINE=InnoDB;
CREATE TABLE sladek(ID_sladka INT NOT NULL AUTO_INCREMENT,login VARCHAR(25) NOT NULL,jmeno VARCHAR(25) NOT NULL,prijmeni VARCHAR(25) NOT NULL,adr_mesto VARCHAR(30) NOT NULL,adr_ulice VARCHAR(30) NOT NULL,adr_cislo_domu INT NOT NULL,PSC INT (5) NOT NULL, PRIMARY KEY (ID_sladka)) ENGINE=InnoDB;
ALTER TABLE pivo ADD CONSTRAINT kod_sladu FOREIGN KEY (ID_slad) REFERENCES slad(ID_slad);
ALTER TABLE pivo ADD CONSTRAINT kod_chmelu FOREIGN KEY (ID_chmel) REFERENCES chmel(ID_chmel);
ALTER TABLE pivo ADD CONSTRAINT kod_kvasnice FOREIGN KEY (ID_kvasnice) REFERENCES kvasnice(ID_kvasnice);
ALTER TABLE pivo ADD CONSTRAINT kod_sladka FOREIGN KEY (ID_sladka) REFERENCES sladek(ID_sladka);
ALTER TABLE pivo ADD CONSTRAINT kod_pivovaru FOREIGN KEY (ID_pivovar) REFERENCES pivovar(ID_pivovar);
ALTER TABLE hodnoceni ADD CONSTRAINT kod1_uzivatel FOREIGN KEY (login) REFERENCES uzivatel(login) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE hodnoceni ADD CONSTRAINT kod2_pivo FOREIGN KEY (ID_pivo) REFERENCES pivo(ID_pivo) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE hodnocenihospoda ADD CONSTRAINT kod2_uzivatel FOREIGN KEY (login) REFERENCES uzivatel(login) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE hodnocenihospoda ADD CONSTRAINT kod3_hospoda FOREIGN KEY (ID_hospoda) REFERENCES hospoda(ID_hospoda) ON DELETE CASCADE ON UPDATE CASCADE;
INSERT INTO slad (barva, puvod, extrakt) VALUES('karamelova', 'Nymburk', 'B335');
INSERT INTO slad (barva, puvod, extrakt) VALUES('svetla', 'Náchod', '16VV');
INSERT INTO slad (barva, puvod, extrakt) VALUES('bavorska', 'Náchod', 'H1Z1');
INSERT INTO chmel (puvod, doba_sklizne, aroma, horkost, podil_alfa_kyselin) VALUES('Zatecko', 'zari', 'prave', '24' ,'8');
INSERT INTO chmel (puvod, doba_sklizne, aroma, horkost, podil_alfa_kyselin) VALUES('Ustecko', 'zari', 'jemne', '32' ,'6');
INSERT INTO chmel (puvod, doba_sklizne, aroma, horkost, podil_alfa_kyselin) VALUES('Trsicko', 'rijen', 'korenene', '13', '5');
INSERT INTO kvasnice (skupenstvi, typ_kvaseni) VALUES('prasek', 'spodní');
INSERT INTO kvasnice (skupenstvi, typ_kvaseni) VALUES('prasek', 'svrchní');
INSERT INTO kvasnice (skupenstvi, typ_kvaseni) VALUES('roztok', 'svrchní');
INSERT INTO pivo (nazev, stupen_EBC, styl_kvaseni, typ_piva, obsah_alkoholu,ID_slad,ID_chmel,ID_kvasnice,ID_sladka,ID_pivovar) VALUES('Janek', '11','svrchni', 'vycepni', '4','1','1','1','1','1');
INSERT INTO pivo (nazev, stupen_EBC, styl_kvaseni, typ_piva, obsah_alkoholu,ID_slad,ID_chmel,ID_kvasnice,ID_sladka,ID_pivovar) VALUES('Lesnik', '11','svrchni', 'vycepni', '5','2','2','2','1','2');
INSERT INTO pivo (nazev, stupen_EBC, styl_kvaseni, typ_piva, obsah_alkoholu,ID_slad,ID_chmel,ID_kvasnice,ID_sladka,ID_pivovar) VALUES('Javor', '11','spodni', 'lezak', '6','2','2','2','1','3');
INSERT INTO pivo (nazev, stupen_EBC, styl_kvaseni, typ_piva, obsah_alkoholu,ID_slad,ID_chmel,ID_kvasnice,ID_sladka,ID_pivovar) VALUES('Doubek', '12','svrchni', 'lezak', '7','1','1','1','1','3');
INSERT INTO uzivatel(login, heslo) VALUES ('Leviathan', 'M89599E');
INSERT INTO uzivatel(login, heslo) VALUES ('Behemoth', 'linac8E');
INSERT INTO uzivatel(login, heslo) VALUES ('Habakkuk', 'hell4ouc8E');
INSERT INTO uzivatel(login, heslo) VALUES ('admin', 'admin');
INSERT INTO hospoda (nazev, adr_mesto, adr_ulice, adr_cislo_domu ,PSC) VALUES('Sokolovna', 'Cheb', 'Failova', '12', '51722');
INSERT INTO hospoda (nazev, adr_mesto, adr_ulice, adr_cislo_domu ,PSC) VALUES('Ruze',  'Jihlava', 'Erbenova', '55', '51366');
INSERT INTO hospoda (nazev, adr_mesto, adr_ulice, adr_cislo_domu ,PSC) VALUES('Platan', 'Pardubice', 'Tylova', '666', '51177');
INSERT INTO pivovar (nazev, adr_mesto, adr_ulice, adr_cislo_domu ,PSC) VALUES('Clock', 'Slemeno', 'Dlouhá', '3', '51933');
INSERT INTO pivovar (nazev, adr_mesto, adr_ulice, adr_cislo_domu ,PSC) VALUES('Rondo', 'Synkov', 'Krátká', '2', '51915');
INSERT INTO pivovar (nazev, adr_mesto, adr_ulice, adr_cislo_domu ,PSC) VALUES('Fortel', 'Rataje', 'Akorát', '1', '51916');
INSERT INTO sladek (login, jmeno, prijmeni, adr_mesto, adr_ulice, adr_cislo_domu ,PSC) VALUES('Habakkuk', 'Havel', 'Prokop', 'Rusnov', 'Jarní', '13', '51719');
INSERT INTO hodnoceni (ID_pivo, login, znamka, datum, cas) VALUES('1', 'Leviathan', '4', '14-8-2012', '10:20');
INSERT INTO hodnoceni (ID_pivo, login, znamka, datum, cas) VALUES('3', 'Behemoth', '6', '6-9-2007', '16:40');
INSERT INTO hodnoceni (ID_pivo, login, znamka, datum, cas) VALUES('2', 'Habakkuk', '7', '1-12-2009', '6:15');
INSERT INTO hodnocenihospoda (ID_hospoda, login, znamka, datum, cas) VALUES('1', 'Leviathan', '4', '14-8-2012', '10:20');
INSERT INTO hodnocenihospoda (ID_hospoda, login, znamka, datum, cas) VALUES('3', 'Behemoth', '6', '6-9-2007', '16:40');
INSERT INTO hodnocenihospoda (ID_hospoda, login, znamka, datum, cas) VALUES('2', 'Habakkuk', '7', '1-12-2009', '6:15');